version: "3.9"

services:
  auth:
    build:
      context: ./auth
    container_name: auth_service
    ports:
      - "8000:8000"
    networks:
      - backend_net

  tourism:
    build:
      context: ./tourism
    container_name: tourism_service
    ports:
      - "8001:8001"
    depends_on:
      - mysql
      - mongo
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=quitogo_db
      - MONGO_URL=mongodb://mongo:27017/
    networks:
      - backend_net

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quitogo_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_net

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
